version: "3.8"

services:
  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hotelmanagement
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_user
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d